default_language_version:
  python: python3.9.14

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        args: [--check]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black
        args: [--check]
  
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "--output", "requirements/base.txt", "--without-hashes"]
        verbose: true
      - id: poetry-export
        args: ["-f", "requirements.txt", "--output", "requirements/local.txt", "--without-hashes", "--with", "dev"]
        verbose: true
