version: "3.9"

services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=txt2hw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  django:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/txt2hw
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure