# Generated by Django 4.1.5 on 2023-01-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('user', 'value'), name='unique_user_value'),
        ),
    ]
